apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: banco-de-dados
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: johnyw/banco-mysql:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
